DELETE FROM ACTIVITY
DELETE FROM CLIENT
DELETE FROM CLIENT_RESERVATION
DELETE FROM INSTRUCTOR
DELETE FROM INSTRUCTOR_CERTIFICATES
DELETE FROM INSTRUCTOR_OCCASIONALSESSION
DELETE FROM INSTRUCTOR_REGULARSESSION
DELETE FROM OCCASIONALACTIVITY
DELETE FROM OCCASIONALACTIVITY_OCCASIONALSESSION
DELETE FROM OCCASIONALSESSION
DELETE FROM REGULARACTIVITY
DELETE FROM REGULARACTIVITY_REGULARSESSION
DELETE FROM REGULARSESSION
DELETE FROM RESERVATION
DELETE FROM SESSION
DELETE FROM SPECIALTY
DELETE FROM SPECIALTY_ACTIVITY
INSERT INTO SPECIALTY (id, description, minimumDuration, certification)VALUES (1, 'Fisioterapia', 20, 'FIS0')
INSERT INTO SPECIALTY (id, description, minimumDuration, certification)VALUES (2, 'Massagem Desportiva', 30, 'MASG')
INSERT INTO SPECIALTY (id, description, minimumDuration, certification)VALUES (3, 'Pilates Clínico', 40, 'FIS1')
INSERT INTO SPECIALTY (id, description, minimumDuration, certification)VALUES (4, 'Pós Parto', 30, 'FIS0')
INSERT INTO INSTRUCTOR (id, name)VALUES (1, 'Uma')
INSERT INTO INSTRUCTOR (id, name)VALUES (2, 'Dona')
INSERT INTO INSTRUCTOR (id, name)VALUES (3, 'Tina')
INSERT INTO INSTRUCTOR_CERTIFICATES (Instructor_ID, CERTIFICATES) VALUES (1, 'FIS0')
INSERT INTO INSTRUCTOR_CERTIFICATES (Instructor_ID, CERTIFICATES) VALUES (1, 'FIS1')
INSERT INTO INSTRUCTOR_CERTIFICATES (Instructor_ID, CERTIFICATES) VALUES (1, 'MASG')
INSERT INTO INSTRUCTOR_CERTIFICATES (Instructor_ID, CERTIFICATES) VALUES (2, 'FIS0')
INSERT INTO INSTRUCTOR_CERTIFICATES (Instructor_ID, CERTIFICATES) VALUES (2, 'MASG')
INSERT INTO INSTRUCTOR_CERTIFICATES (Instructor_ID, CERTIFICATES) VALUES (3, 'MASG')

